const PIN='7900';
const STORE='poolside-pulse-v3-pro-20260602';
const DEFAULT_ADDRESS='615 Serenity Shores Ln, Kimberling City, MO 65686';
const DEFAULT={
  admin:false, view:'home', adminTab:'station', platform:'suno',
  playlistName:'Serenity Shores Poolside Radio', playlistUrl:'https://suno.com/playlist/cf4b536e-9005-4c98-9ea5-a7f01eca116f',
  tracks:[{title:'Import your Suno playlist',artist:'Serenity Shores',duration:'3:00',audioUrl:''}], current:0, playing:false,
  volume:1, voiceName:'', voiceRate:.92, voicePitch:1,
  address:DEFAULT_ADDRESS, lat:'', lon:'', accuracy:'', radius:10, weatherOn:true, lastWeather:'Tap Verify Resort Location in admin to activate the 10-mile weather monitor.',
  instant:'Attention guests, this is a Serenity Shores pool announcement.',
  ownerMsg:'Welcome to Serenity Shores. We hope your family has an unforgettable day at the lake and pool.',
  managerMsg:'Pool reminder: children must be supervised, glass is not permitted, and safety comes first.',
  birthdayName:'', birthdayMsg:'Happy birthday from Serenity Shores. We hope your day is absolutely wonderful.',
  schedules:[], events:[eventObj('Version 3 Pro ready')]
};
let S=load(); let audio=new Audio(); let voices=[]; audio.volume=S.volume; audio.onended=()=>skip(1);
function eventObj(text,type='info'){return {text,type,time:new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}}
function load(){try{return normalize({...DEFAULT,...JSON.parse(localStorage.getItem(STORE)||'{}')})}catch{return {...DEFAULT}}}
function normalize(x){x.tracks=Array.isArray(x.tracks)&&x.tracks.length?x.tracks:DEFAULT.tracks;x.schedules=Array.isArray(x.schedules)?x.schedules:[];x.events=Array.isArray(x.events)?x.events:DEFAULT.events;x.current=Math.min(Math.max(+x.current||0,0),Math.max(x.tracks.length-1,0));return x}
function save(){localStorage.setItem(STORE,JSON.stringify(S))}
function log(text,type='info'){S.events=[eventObj(text,type),...(S.events||[])].slice(0,60);save()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function $(id){return document.getElementById(id)}
function val(id){return $(id)?.value||''}
function track(){return S.tracks[S.current]||{title:'No track selected',artist:'Station',duration:'0:00',audioUrl:''}}
function pickBestVoice(){const names=voices.map(v=>v.name.toLowerCase());const prefer=['siri','samantha','ava','allison','google us english','microsoft aria','premium','enhanced','natural'];let best=voices.find(v=>/en[-_]?us/i.test(v.lang||'')&&prefer.some(p=>v.name.toLowerCase().includes(p)))||voices.find(v=>/^en/i.test(v.lang||''))||voices[0];if(best){S.voiceName=best.name;save()}}
function speak(text,repeats=1,delay=0){const msg=String(text||'').trim();if(!msg)return;if(!('speechSynthesis' in window)){alert('This browser does not support text-to-speech.');return}speechSynthesis.cancel();let i=0;const total=Math.max(1,+repeats||1);const wait=Math.max(0,+delay||0)*1000;const go=()=>{const u=new SpeechSynthesisUtterance(msg);const chosen=voices.find(v=>v.name===S.voiceName);if(chosen)u.voice=chosen;u.rate=+S.voiceRate||.92;u.pitch=+S.voicePitch||1;u.volume=+S.volume||1;u.onend=()=>{i++;if(i<total)setTimeout(go,wait)};speechSynthesis.speak(u)};go();log('Spoken announcement: '+msg.slice(0,90),'voice');render()}
function play(){S.playing=true;const t=track();if(t.audioUrl){audio.src=t.audioUrl;audio.play().catch(()=>alert('This song title is loaded, but the direct audio stream is protected or unavailable. Suno playback may continue in its own player; this station still controls queue, announcements, and safety overrides.'))}log('Now playing: '+t.title,'music');save();render()}
function pause(){audio.pause();S.playing=false;save();render()}
function skip(n){if(!S.tracks.length)return;S.current=(S.current+n+S.tracks.length)%S.tracks.length;log((n>0?'Skipped to ':'Returned to ')+track().title,'music');if(S.playing)play();else{save();render()}}
async function importPlaylist(){S.platform=val('platform')||S.platform;S.playlistName=val('playlistName')||S.playlistName;S.playlistUrl=val('playlistUrl')||S.playlistUrl;save();log('Importing playlist...','music');render();try{if(S.platform!=='suno')throw Error('Automatic import is currently built for Suno. Other platform links can be saved as station references.');const r=await fetch('/api/suno-playlist?url='+encodeURIComponent(S.playlistUrl));const d=await r.json();if(!r.ok||!d.ok||!Array.isArray(d.tracks)||!d.tracks.length)throw Error(d.error||'No tracks found');S.tracks=d.tracks.map(t=>({title:t.title||'Untitled',artist:t.artist||'Suno',duration:t.duration||'3:00',audioUrl:t.audioUrl||'',sourceUrl:t.sourceUrl||''}));if(d.playlistName)S.playlistName=d.playlistName;S.current=0;log('Imported '+S.tracks.length+' playlist tracks','music');save();render()}catch(err){alert('Import needs attention: '+err.message);log('Import failed: '+err.message,'warn');render()}}
function saveStation(){S.platform=val('platform');S.playlistName=val('playlistName');S.playlistUrl=val('playlistUrl');save();log('Station settings saved','music');render()}
function bulkImport(){const rows=val('bulkTracks').split('\n').map(x=>x.trim()).filter(Boolean);if(!rows.length)return alert('Paste at least one song line.');S.tracks=rows.map(r=>{const p=r.split('|').map(x=>x.trim());return {title:p[0]||'Untitled',artist:p[1]||'Unknown',duration:p[2]||'3:00',audioUrl:p[3]||''}});S.current=0;save();log('Bulk imported '+S.tracks.length+' songs','music');render()}
async function verifyAddress(){S.address=val('address')||DEFAULT_ADDRESS;log('Verifying resort location...','weather');render();try{const r=await fetch('/api/geocode?address='+encodeURIComponent(S.address));const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Address not found');S.lat=String(d.latitude);S.lon=String(d.longitude);S.accuracy='Address match';S.lastWeather='Location verified: '+(d.matchedAddress||S.address);log('Location verified','weather');save();render()}catch(err){alert('Could not verify address. Use device location or enter coordinates. '+err.message);log('Location verification failed','warn');render()}}
function useDeviceLocation(){if(!navigator.geolocation)return alert('This browser does not support device location.');navigator.geolocation.getCurrentPosition(pos=>{S.lat=pos.coords.latitude.toFixed(6);S.lon=pos.coords.longitude.toFixed(6);S.accuracy=Math.round(pos.coords.accuracy||0)+' meter device estimate';S.lastWeather='Device location captured. Confirm the phone is at the pool sound system or resort office.';log('Device GPS captured','weather');save();render()},()=>alert('Location permission was denied or unavailable.'),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
async function checkWeather(){const lat=+S.lat,lon=+S.lon;if(!lat||!lon){S.lastWeather='Verify location first.';save();render();return}log('Checking 10-mile weather radius...','weather');render();try{const r=await fetch(`/api/weather?lat=${lat}&lon=${lon}&radiusMiles=${+S.radius||10}`);const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Weather check failed');S.lastWeather=d.summary;if(d.threat){pause();speak('Attention guests. Weather activity has been detected near Serenity Shores. Please exit the pool area and move indoors immediately.');log('Weather safety override triggered','alert')}else log('Weather clear: '+d.summary,'weather');save();render()}catch(err){S.lastWeather='Weather check failed: '+err.message;log(S.lastWeather,'warn');save();render()}}
function quick(text){S.instant=text;speak(text,1,0);save()}
function saveAnnouncementFields(){S.instant=val('instant');S.ownerMsg=val('ownerMsg');S.managerMsg=val('managerMsg');S.birthdayMsg=val('birthdayMsg');save();log('Announcement templates saved','voice');render()}
function addSchedule(){const msg=val('scheduleMsg');const first=val('scheduleTime');const repeat=+val('scheduleRepeat')||1;const interval=+val('scheduleInterval')||5;if(!msg)return alert('Add the announcement text first.');S.schedules.unshift({id:Date.now(),msg,next:first?new Date(first).getTime():Date.now()+60000,repeat,interval,done:0,on:true});save();log('Scheduled announcement created','schedule');render()}
function tickSchedules(){let changed=false;const now=Date.now();(S.schedules||[]).forEach(s=>{if(!s.on||s.done>=s.repeat||now<s.next)return;speak(s.msg,1,0);s.done++;s.next=now+s.interval*60000;if(s.done>=s.repeat)s.on=false;changed=true});if(changed){save();render()}}
function setView(view,tab){S.view=view;if(tab)S.adminTab=tab;save();render()}
function shell(content){return `<div class="page"><header class="topbar"><div class="brand"><span class="mark">SS</span><div><b>Serenity Shores</b><small>Poolside Radio</small></div></div><button class="adminAccess" id="adminBtn">${S.admin?'Command Center':'Admin'}</button></header>${content}</div>`}
function publicHome(){const t=track();return shell(`<main class="public"><section class="heroPro"><div class="heroText"><span class="pill">LIVE RESORT STATION</span><h1>Poolside Radio</h1><p>Music, pool updates, birthdays, daily messages, and weather-aware safety announcements for Serenity Shores guests.</p><div class="heroActions"><button id="homePlay">${S.playing?'Pause Station':'Play Station'}</button><button class="soft" id="homeSkip">Skip Song</button></div></div><div class="weatherBadge"><b>Weather Monitor</b><span>${esc(S.lastWeather)}</span></div></section><section class="stationCard"><div class="albumArt"><span>SS</span><b>Radio</b></div><div class="stationInfo"><p class="eyebrow">NOW PLAYING</p><h2>${esc(t.title)}</h2><p>${esc(t.artist)} · ${esc(t.duration)}</p><div class="meter"><i></i></div><p class="muted">${esc(S.playlistName)}</p></div></section><section class="publicGrid"><div class="panel"><h3>Up Next</h3>${S.tracks.slice(S.current+1,S.current+5).map(t=>`<div class="miniSong"><b>${esc(t.title)}</b><span>${esc(t.artist)}</span></div>`).join('')||'<p class="muted">End of queue.</p>'}</div><div class="panel"><h3>Today at the Pool</h3><p>${esc(S.ownerMsg)}</p><p>${esc(S.managerMsg)}</p></div></section></main>`)}
function login(){return shell(`<main class="adminPage"><section class="loginCard"><h1>Command Center</h1><p>Admin controls are protected. Home remains public.</p><input id="pin" type="password" inputmode="numeric" placeholder="Enter PIN"><button id="login">Enter Admin</button><small>PIN 7900</small></section></main>`)}
function adminShell(body){const tabs=[['station','Station'],['ann','Announcements'],['program','Daily Plan'],['weather','Weather'],['voice','Voice']];return shell(`<main class="adminPage"><aside class="rail">${tabs.map(([id,label])=>`<button data-tab="${id}" class="${S.adminTab===id?'on':''}">${label}</button>`).join('')}<button class="ghost" id="publicView">Public Home</button></aside><section class="workspace">${body}</section></main>`)}
function stationAdmin(){return adminShell(`<div class="workHeader"><p class="eyebrow">STATION CONTROL</p><h1>Music Source & Queue</h1><p>Use Suno as the working station source. Other platforms can be saved as references while we add deeper integrations.</p></div><div class="panel"><div class="two"><label>Platform<select id="platform"><option value="suno">Suno Playlist</option><option value="youtube">YouTube Reference</option><option value="spotify">Spotify Reference</option><option value="amazon">Amazon Reference</option></select></label><label>Playlist Name<input id="playlistName" value="${esc(S.playlistName)}"></label></div><label>Playlist URL<input id="playlistUrl" value="${esc(S.playlistUrl)}"></label><div class="buttonRow"><button id="saveStation">Save</button><button id="importPlaylist">Import From Suno</button><button class="soft" id="adminPlay">${S.playing?'Pause':'Play'}</button><button class="soft" id="adminSkip">Skip</button></div></div><div class="panel"><h2>Queue</h2>${S.tracks.map((t,i)=>`<div class="queueRow ${i===S.current?'current':''}"><span>${i+1}</span><div><b>${esc(t.title)}</b><small>${esc(t.artist)} · ${esc(t.duration)}</small></div><button data-playtrack="${i}">Play</button></div>`).join('')}</div><div class="panel"><h2>Bulk Import Backup</h2><p class="muted">Format: Title | Artist | Duration | optional direct audio URL</p><textarea id="bulkTracks">${S.tracks.map(t=>`${t.title} | ${t.artist} | ${t.duration} | ${t.audioUrl||''}`).join('\n')}</textarea><button id="bulkImport">Replace Queue From Text</button></div>`)}
function announcementsAdmin(){return adminShell(`<div class="workHeader"><p class="eyebrow">ANNOUNCEMENTS</p><h1>Instant Messages & Templates</h1></div><div class="panel"><h2>Speak Now</h2><textarea id="instant">${esc(S.instant)}</textarea><div class="buttonRow"><button id="speakNow">Speak Immediately</button><button class="soft" id="closeUmbrellas">Close Umbrellas</button><button class="soft" id="poolClosing">Pool Closing Soon</button></div></div><div class="two"><div class="panel"><h2>Birthday Greeting</h2><input id="birthdayName" placeholder="Guest name" value="${esc(S.birthdayName)}"><textarea id="birthdayMsg">${esc(S.birthdayMsg)}</textarea><button id="birthdaySpeak">Speak Birthday</button></div><div class="panel"><h2>Owner / Manager Daily Messages</h2><label>Owner Message<textarea id="ownerMsg">${esc(S.ownerMsg)}</textarea></label><label>Manager Message<textarea id="managerMsg">${esc(S.managerMsg)}</textarea></label><button id="saveAnnouncements">Save Templates</button></div></div>`)}
function programAdmin(){return adminShell(`<div class="workHeader"><p class="eyebrow">DAILY PROGRAMMING</p><h1>Schedule Announcements</h1><p>Paste announcements, choose first play time, repeat count, and interval.</p></div><div class="panel"><textarea id="scheduleMsg" placeholder="Announcement text"></textarea><div class="three"><input id="scheduleTime" type="datetime-local"><input id="scheduleRepeat" type="number" value="3" min="1"><input id="scheduleInterval" type="number" value="10" min="1"></div><button id="addSchedule">Add Scheduled Announcement</button></div><div class="panel"><h2>Schedule</h2>${S.schedules.map(s=>`<div class="queueRow"><div><b>${esc(s.msg)}</b><small>${s.done}/${s.repeat} played · ${s.on?'next '+new Date(s.next).toLocaleString():'complete'}</small></div><button data-deleteSchedule="${s.id}">Delete</button></div>`).join('')||'<p class="muted">No scheduled announcements yet.</p>'}</div>`)}
function weatherAdmin(){return adminShell(`<div class="workHeader"><p class="eyebrow">WEATHER & SAFETY</p><h1>Location Verification</h1><p>Defaulted to Serenity Shores. Verify once, then the app checks a ${esc(S.radius)}-mile radius.</p></div><div class="panel"><label>Resort Address<input id="address" value="${esc(S.address)}"></label><div class="buttonRow"><button id="verifyAddress">Verify Resort Address</button><button class="soft" id="deviceLocation">Use Device Location</button><button class="soft" id="weatherNow">Check Weather Now</button></div><div class="three"><label>Latitude<input id="lat" value="${esc(S.lat)}"></label><label>Longitude<input id="lon" value="${esc(S.lon)}"></label><label>Radius Miles<input id="radius" type="number" value="${esc(S.radius)}"></label></div><button id="saveLocation">Save Location</button><div class="statusBox"><b>Status</b><p>${esc(S.lastWeather)}</p><small>${S.lat&&S.lon?`GPS: ${esc(S.lat)}, ${esc(S.lon)} · ${esc(S.accuracy||'verified')}`:'GPS not verified yet.'}</small></div></div>`)}
function voiceAdmin(){const opts=voices.map(v=>`<option value="${esc(v.name)}" ${v.name===S.voiceName?'selected':''}>${esc(v.name)} ${v.lang?'· '+esc(v.lang):''}</option>`).join('');return adminShell(`<div class="workHeader"><p class="eyebrow">VOICE STUDIO</p><h1>Make Alerts Sound Better</h1><p>This uses the best voice built into the device/browser. Choose the most natural voice available on the iPhone or Mac connected to the speakers.</p></div><div class="panel"><label>Voice<select id="voiceName"><option value="">Default Device Voice</option>${opts}</select></label><button id="bestVoice">Use Best Available Voice</button><label>Speaking Speed<input id="voiceRate" type="range" min="0.75" max="1.15" step="0.01" value="${esc(S.voiceRate)}"></label><label>Pitch<input id="voicePitch" type="range" min="0.85" max="1.15" step="0.01" value="${esc(S.voicePitch)}"></label><div class="buttonRow"><button id="saveVoice">Save Voice</button><button class="soft" id="testVoice">Test Voice</button></div></div>`)}
function render(){let html;if(S.view==='home')html=publicHome();else if(!S.admin)html=login();else html=({station:stationAdmin,ann:announcementsAdmin,program:programAdmin,weather:weatherAdmin,voice:voiceAdmin}[S.adminTab]||stationAdmin)();document.getElementById('app').innerHTML=html;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.adminTab=b.dataset.tab;S.view='admin';save();render()});const adminBtn=$('adminBtn');if(adminBtn)adminBtn.onclick=()=>{S.view=S.admin?'admin':'login';save();render()};if($('publicView'))$('publicView').onclick=()=>setView('home');if($('login'))$('login').onclick=()=>{if(val('pin')===PIN){S.admin=true;S.view='admin';S.adminTab='station';save();render()}else alert('Wrong PIN')};if($('homePlay'))$('homePlay').onclick=()=>S.playing?pause():play();if($('homeSkip'))$('homeSkip').onclick=()=>skip(1);if($('platform'))$('platform').value=S.platform;if($('saveStation'))$('saveStation').onclick=saveStation;if($('importPlaylist'))$('importPlaylist').onclick=importPlaylist;if($('adminPlay'))$('adminPlay').onclick=()=>S.playing?pause():play();if($('adminSkip'))$('adminSkip').onclick=()=>skip(1);if($('bulkImport'))$('bulkImport').onclick=bulkImport;document.querySelectorAll('[data-playtrack]').forEach(b=>b.onclick=()=>{S.current=+b.dataset.playtrack;play()});if($('speakNow'))$('speakNow').onclick=()=>{S.instant=val('instant');save();speak(S.instant)};if($('closeUmbrellas'))$('closeUmbrellas').onclick=()=>quick('Attention guests, please close all umbrellas and secure loose items. Thank you.');if($('poolClosing'))$('poolClosing').onclick=()=>quick('Attention guests, the pool will be closing soon. Please gather your belongings.');if($('birthdaySpeak'))$('birthdaySpeak').onclick=()=>{S.birthdayName=val('birthdayName');S.birthdayMsg=val('birthdayMsg');save();speak(`Happy birthday ${S.birthdayName}. ${S.birthdayMsg}`)};if($('saveAnnouncements'))$('saveAnnouncements').onclick=saveAnnouncementFields;if($('addSchedule'))$('addSchedule').onclick=addSchedule;document.querySelectorAll('[data-deleteSchedule]').forEach(b=>b.onclick=()=>{S.schedules=S.schedules.filter(s=>String(s.id)!==String(b.dataset.deleteSchedule));save();render()});if($('verifyAddress'))$('verifyAddress').onclick=verifyAddress;if($('deviceLocation'))$('deviceLocation').onclick=useDeviceLocation;if($('weatherNow'))$('weatherNow').onclick=checkWeather;if($('saveLocation'))$('saveLocation').onclick=()=>{S.address=val('address');S.lat=val('lat');S.lon=val('lon');S.radius=+val('radius')||10;save();render()};if($('bestVoice'))$('bestVoice').onclick=()=>{pickBestVoice();render()};if($('saveVoice'))$('saveVoice').onclick=()=>{S.voiceName=val('voiceName');S.voiceRate=val('voiceRate');S.voicePitch=val('voicePitch');save();render()};if($('testVoice'))$('testVoice').onclick=()=>speak('This is the Serenity Shores Poolside Radio voice test. Please exit the pool area if directed by staff.');}
function loadVoices(){voices=speechSynthesis.getVoices()||[];if(!S.voiceName&&voices.length)pickBestVoice();render()}
if('speechSynthesis' in window){speechSynthesis.onvoiceschanged=loadVoices;loadVoices()}else render();setInterval(tickSchedules,10000);setInterval(()=>S.weatherOn&&S.lat&&S.lon&&checkWeather(),300000);
