const PIN='7900';
const STORE='poolside-pulse-v3';
const DEFAULT_ADDRESS='615 Serenity Shores Ln, Kimberling City, MO 65686';
const DEFAULT={admin:false,view:'home',platform:'suno',playlistName:'Serenity Shores Radio',playlistUrl:'https://suno.com/playlist/cf4b536e-9005-4c98-9ea5-a7f01eca116f',tracks:[{title:'Poolside Welcome',artist:'Serenity Shores',duration:'3:00',audioUrl:''},{title:'Lake Day Energy',artist:'Suno',duration:'3:10',audioUrl:''}],current:0,playing:false,voiceName:'',voiceRate:0.95,voicePitch:1,volume:1,address:DEFAULT_ADDRESS,lat:'',lon:'',radius:10,lastWeather:'Location ready for verification.',weatherOn:true,instant:'Welcome to Serenity Shores. Please enjoy the pool and watch your children carefully.',ownerMsg:'Welcome to Serenity Shores. We are glad your family is here.',birthdayName:'',birthdayMsg:'Happy birthday from Serenity Shores!',schedules:[],events:[['System ready',stamp()]]};
let S=load(),A=new Audio(),voices=[];A.onended=()=>skip(1);A.volume=S.volume;
function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return {...DEFAULT}}}
function save(){localStorage.setItem(STORE,JSON.stringify(S))}
function stamp(){return new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function e(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function log(x){S.events=[[x,stamp()],...(S.events||[])].slice(0,40);save()}
function current(){return S.tracks[S.current]||{title:'No track',artist:'Admin',duration:'0:00',audioUrl:''}}
function speak(txt,repeats=1,delay=0){let msg=String(txt||'').trim();if(!msg)return;if(!('speechSynthesis'in window)){alert('This browser does not support speech.');return}speechSynthesis.cancel();let i=0;function go(){let u=new SpeechSynthesisUtterance(msg);let v=voices.find(v=>v.name===S.voiceName);if(v)u.voice=v;u.rate=+S.voiceRate||1;u.pitch=+S.voicePitch||1;u.volume=+S.volume||1;u.onend=()=>{if(++i<repeats)setTimeout(go,delay*1000)};speechSynthesis.speak(u)}go();log('Spoken: '+msg.slice(0,80));render()}
function play(){let t=current();S.playing=true;if(t.audioUrl){A.src=t.audioUrl;A.play().catch(()=>alert('This track URL did not play. The queue still tracks song order.'))}log('Playing: '+t.title);save();render()}
function pause(){A.pause();S.playing=false;save();render()}
function skip(n=1){S.current=(S.current+n+S.tracks.length)%S.tracks.length;if(S.playing)play();else{log('Selected: '+current().title);save();render()}}
async function suno(){S.playlistName=v('playlistName');S.playlistUrl=v('playlistUrl');log('Importing playlist...');render();try{let r=await fetch('/api/suno-playlist?url='+encodeURIComponent(S.playlistUrl));let d=await r.json();if(!r.ok||!d.ok||!d.tracks?.length)throw Error(d.error||'No tracks found');S.tracks=d.tracks.map(x=>({title:x.title||'Untitled',artist:x.artist||'Suno',duration:x.duration||'3:00',audioUrl:x.audioUrl||'',sourceUrl:x.sourceUrl||''}));if(d.playlistName)S.playlistName=d.playlistName;S.current=0;log('Imported '+S.tracks.length+' tracks');save();render()}catch(err){alert('Playlist import failed: '+err.message);log('Import failed: '+err.message);render()}}
async function geo(){S.address=v('address')||DEFAULT_ADDRESS;log('Verifying location...');render();try{let r=await fetch('/api/geocode?address='+encodeURIComponent(S.address));let d=await r.json();if(!d.ok)throw Error(d.error||'No match');S.lat=d.latitude;S.lon=d.longitude;S.lastWeather='Verified: '+(d.matchedAddress||S.address);log('Location verified');save();render()}catch(err){alert('Could not verify address. You can type latitude/longitude. '+err.message);log('Location verification failed')}}
async function weather(){let lat=+S.lat,lon=+S.lon;if(!lat||!lon){S.lastWeather='Verify the resort location first.';save();render();return}log('Checking weather...');render();try{let r=await fetch(`/api/weather?lat=${lat}&lon=${lon}&radiusMiles=${+S.radius||10}`);let d=await r.json();if(!d.ok)throw Error(d.error||'Weather failed');S.lastWeather=d.summary;if(d.threat){pause();speak('Attention guests. '+S.lastWeather+' Please exit the pool and seek shelter indoors.',1,0)}log('Weather: '+S.lastWeather);save();render()}catch(err){S.lastWeather='Weather check failed: '+err.message;save();render()}}
function addSchedule(){let msg=v('scheduleMsg'), first=v('scheduleTime'), repeat=+v('scheduleRepeat')||1, interval=+v('scheduleInterval')||5;if(!msg)return alert('Add a message first.');S.schedules.unshift({id:Date.now(),msg,next:first?new Date(first).getTime():Date.now()+60000,repeat,interval,done:0,on:true});log('Scheduled announcement added');save();render()}
function tick(){let now=Date.now(),changed=false;(S.schedules||[]).forEach(s=>{if(!s.on||s.done>=s.repeat||now<s.next)return;speak(s.msg,1,0);s.done++;s.next=now+s.interval*60000;if(s.done>=s.repeat)s.on=false;changed=true});if(changed){save();render()}}
function platformHelp(){return S.platform==='youtube'?'Paste a YouTube playlist or video URL. Version 3 tracks it as a station source; full YouTube player control can be added next.':S.platform==='spotify'?'Spotify support is limited by Premium/commercial restrictions. Use as a reference source for now.':'Suno is the primary working music source.'}
function top(){return `<header class="hero"><div><b>Serenity Shores</b><h1>Poolside Radio</h1><p>A private resort station for music, announcements, birthdays, daily messages, and pool safety.</p></div><button id="adminBtn">${S.admin?'Admin Open':'Admin'}</button></header>`}
function nav(){if(!S.admin)return '';let tabs=[['station','Station'],['ann','Announcements'],['weather','Weather'],['voice','Voice Studio'],['program','Daily Programming']];return `<nav class="tabs">${tabs.map(t=>`<button class="${S.view===t[0]?'on':''}" data-view="${t[0]}">${t[1]}</button>`).join('')}</nav>`}
function home(){let t=current();return `${top()}${nav()}<main><section class="card now"><div class="cover">SS<br><span>Radio</span></div><div><p class="label">NOW PLAYING</p><h2>${e(t.title)}</h2><p>${e(t.artist)} · ${e(t.duration)}</p><p>${e(S.playlistName)}</p></div></section><section class="grid"><div class="card"><h3>Up Next</h3>${S.tracks.slice(S.current+1,S.current+5).map(row).join('')||'<p>End of queue.</p>'}</div><div class="card"><h3>Today at the Pool</h3><p>${e(S.ownerMsg)}</p><p><b>Weather:</b> ${e(S.lastWeather)}</p></div></section></main>`}
function login(){return `${top()}<main><section class="card login"><h2>Admin Access</h2><input id="pin" placeholder="PIN" type="password"><button id="login">Enter</button><p>PIN: 7900</p></section></main>`}
function station(){return `${top()}${nav()}<main><section class="card"><h2>Station Control</h2><label>Platform<select id="platform"><option value="suno">Suno</option><option value="youtube">YouTube</option><option value="spotify">Spotify Reference</option><option value="amazon">Amazon Reference</option></select></label><p>${e(platformHelp())}</p><label>Playlist Name<input id="playlistName" value="${e(S.playlistName)}"></label><label>Playlist URL<input id="playlistUrl" value="${e(S.playlistUrl)}"></label><button id="import">Import / Refresh Playlist</button><button id="play">${S.playing?'Pause':'Play'}</button><button id="prev">Previous</button><button id="next">Skip</button></section><section class="card"><h2>Queue</h2>${S.tracks.map((t,i)=>`<div class="song ${i===S.current?'active':''}"><span>${i+1}</span><b>${e(t.title)}</b><small>${e(t.artist)}</small><button data-set="${i}">Play</button></div>`).join('')}</section></main>`}
function ann(){return `${top()}${nav()}<main><section class="card"><h2>Speak Now</h2><textarea id="instant">${e(S.instant)}</textarea><button id="speak">Speak Immediately</button></section><section class="grid"><div class="card"><h3>Birthday Greeting</h3><input id="bday" placeholder="Guest name" value="${e(S.birthdayName)}"><button id="birthday">Speak Birthday</button></div><div class="card"><h3>Owner / Manager Message</h3><textarea id="ownerMsg">${e(S.ownerMsg)}</textarea><button id="saveOwner">Save</button></div></section></main>`}
function program(){return `${top()}${nav()}<main><section class="card"><h2>Daily Programming</h2><textarea id="scheduleMsg">${e(S.scheduleMsg||'')}</textarea><div class="three"><input id="scheduleTime" type="datetime-local"><input id="scheduleRepeat" type="number" value="3"><input id="scheduleInterval" type="number" value="5"></div><button id="addSchedule">Schedule Message</button></section><section class="card"><h2>Scheduled Announcements</h2>${(S.schedules||[]).map(s=>`<div class="song"><b>${e(s.msg)}</b><small>${s.done}/${s.repeat} played · ${s.on?'next '+new Date(s.next).toLocaleString():'complete'}</small><button data-del="${s.id}">Delete</button></div>`).join('')||'<p>No schedules.</p>'}</section></main>`}
function weatherScreen(){return `${top()}${nav()}<main><section class="card"><h2>Weather & Safety Location</h2><label>Resort Address<input id="address" value="${e(S.address)}"></label><button id="geo">Verify Location</button><button id="useDevice">Use This Device Location</button><div class="three"><input id="lat" placeholder="Latitude" value="${e(S.lat)}"><input id="lon" placeholder="Longitude" value="${e(S.lon)}"><input id="radius" type="number" value="${e(S.radius)}"></div><button id="saveLocation">Save Location</button><button id="weatherCheck">Check Weather Now</button><p>${e(S.lastWeather)}</p></section></main>`}
function voice(){let opts=voices.map(v=>`<option ${v.name===S.voiceName?'selected':''}>${e(v.name)}</option>`).join('');return `${top()}${nav()}<main><section class="card"><h2>Voice Studio</h2><p>Choose the most natural device voice available. Premium cloud voices can be added later.</p><select id="voiceName"><option value="">Default Voice</option>${opts}</select><label>Rate<input id="rate" type="range" min="0.7" max="1.2" step="0.05" value="${S.voiceRate}"></label><label>Pitch<input id="pitch" type="range" min="0.8" max="1.2" step="0.05" value="${S.voicePitch}"></label><button id="saveVoice">Save Voice</button><button id="testVoice">Test Voice</button></section></main>`}
function row(t){return `<p class="row"><b>${e(t.title)}</b><span>${e(t.artist)}</span></p>`}
function render(){let html=S.view==='home'?home():!S.admin?login():({station,ann,weather:weatherScreen,voice,program}[S.view]||station)();document.getElementById('app').innerHTML=html;bind()}
function v(id){return document.getElementById(id)?.value||''}
function bind(){let q=s=>document.querySelector(s);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;save();render()});if(q('#adminBtn'))q('#adminBtn').onclick=()=>{S.view=S.admin?'station':'login';save();render()};if(q('#login'))q('#login').onclick=()=>{if(v('pin')===PIN){S.admin=true;S.view='station';save();render()}else alert('Wrong PIN')};if(q('#platform')){q('#platform').value=S.platform;q('#platform').onchange=()=>{S.platform=v('platform');save();render()}}if(q('#import'))q('#import').onclick=suno;if(q('#play'))q('#play').onclick=()=>S.playing?pause():play();if(q('#prev'))q('#prev').onclick=()=>skip(-1);if(q('#next'))q('#next').onclick=()=>skip(1);document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{S.current=+b.dataset.set;play()});if(q('#speak'))q('#speak').onclick=()=>{S.instant=v('instant');save();speak(S.instant)};if(q('#birthday'))q('#birthday').onclick=()=>{S.birthdayName=v('bday');speak(`Happy birthday ${S.birthdayName}. ${S.birthdayMsg}`);save()};if(q('#saveOwner'))q('#saveOwner').onclick=()=>{S.ownerMsg=v('ownerMsg');save();render()};if(q('#addSchedule'))q('#addSchedule').onclick=addSchedule;document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{S.schedules=S.schedules.filter(s=>String(s.id)!==String(b.dataset.del));save();render()});if(q('#geo'))q('#geo').onclick=geo;if(q('#useDevice'))q('#useDevice').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{S.lat=p.coords.latitude.toFixed(6);S.lon=p.coords.longitude.toFixed(6);S.lastWeather='Device location captured. Verify it is at the resort sound system.';save();render()},()=>alert('Location permission failed.'));if(q('#saveLocation'))q('#saveLocation').onclick=()=>{S.address=v('address');S.lat=v('lat');S.lon=v('lon');S.radius=+v('radius')||10;save();render()};if(q('#weatherCheck'))q('#weatherCheck').onclick=weather;if(q('#saveVoice'))q('#saveVoice').onclick=()=>{S.voiceName=v('voiceName');S.voiceRate=v('rate');S.voicePitch=v('pitch');save();render()};if(q('#testVoice'))q('#testVoice').onclick=()=>speak('This is the Serenity Shores resort radio voice test.');}
function loadVoices(){voices=speechSynthesis?.getVoices?.()||[];render()}
if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=loadVoices;loadVoices()}else render();setInterval(tick,10000);setInterval(()=>S.weatherOn&&weather(),300000);