const VERSION='3.1';
const PIN='7900';
const KEY='poolside-radio-v31';
const DEFAULT_ADDRESS='615 Serenity Shores Ln, Kimberling City, MO 65686';
const BASE={admin:false,screen:'home',tab:'station',playlistName:'Serenity Shores Poolside Radio',playlistUrl:'https://suno.com/playlist/cf4b536e-9005-4c98-9ea5-a7f01eca116f',platform:'suno',tracks:[{title:'Import your Suno playlist',artist:'Serenity Shores',duration:'3:00',audioUrl:''}],current:0,playing:false,voiceMode:'ai',aiVoice:'marin',deviceVoice:'',voiceRate:.92,voicePitch:1,address:DEFAULT_ADDRESS,lat:'',lon:'',radius:10,locationNote:'Ready to verify Serenity Shores location.',weather:'Verify location to start weather monitoring.',instant:'Attention guests, this is a Serenity Shores pool announcement.',owner:'Welcome to Serenity Shores. We hope your family has an unforgettable day at the lake and pool.',manager:'Pool reminder: children must be supervised, glass is not permitted, and safety comes first.',birthdayName:'',birthdayText:'Happy birthday from Serenity Shores. We hope your day is absolutely wonderful.',schedule:[],log:[['Version 3.1 loaded',now()]]};
let S=load(), voices=[], audio=new Audio(); audio.onended=()=>skip(1);
function now(){return new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function load(){try{return clean({...BASE,...JSON.parse(localStorage.getItem(KEY)||'{}')})}catch{return {...BASE}}}
function clean(s){s.tracks=Array.isArray(s.tracks)&&s.tracks.length?s.tracks:BASE.tracks;s.schedule=Array.isArray(s.schedule)?s.schedule:[];s.log=Array.isArray(s.log)?s.log:BASE.log;s.current=Math.min(Math.max(+s.current||0,0),Math.max(s.tracks.length-1,0));return s}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function log(x){S.log=[[x,now()],...(S.log||[])].slice(0,50);save()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function $(id){return document.getElementById(id)}; function val(id){return $(id)?.value||''}
function tr(){return S.tracks[S.current]||{title:'No track',artist:'Station',duration:'0:00',audioUrl:''}}
function set(screen,tab){S.screen=screen;if(tab)S.tab=tab;save();render()}
function bestVoices(){return voices.filter(v=>/^en/i.test(v.lang||'')).sort((a,b)=>score(b)-score(a)).slice(0,10)}
function score(v){let n=(v.name+' '+v.lang).toLowerCase(),s=0;['samantha','ava','allison','siri','premium','enhanced','natural','google','microsoft','aria'].forEach((p,i)=>{if(n.includes(p))s+=20-i});if(n.includes('en-us'))s+=10;return s}
async function speak(text){let msg=String(text||'').trim();if(!msg)return;if(S.voiceMode==='ai'){try{let r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:msg,voice:S.aiVoice,instructions:'Speak like a calm, polished, friendly resort announcer. Safety messages should be firm but not panicked.'})});if(r.ok){let blob=await r.blob();let url=URL.createObjectURL(blob);let a=new Audio(url);a.volume=1;await a.play();log('AI voice announcement played');return}else{let d=await r.json().catch(()=>({error:'AI voice unavailable'}));alert(d.error||'AI voice unavailable. Falling back to device voice.')}}catch(e){alert('AI voice failed. Falling back to device voice. '+e.message)}}
 if(!('speechSynthesis'in window)){alert('Speech is not supported on this browser.');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(msg);let v=voices.find(v=>v.name===S.deviceVoice)||bestVoices()[0];if(v)u.voice=v;u.rate=+S.voiceRate||.92;u.pitch=+S.voicePitch||1;speechSynthesis.speak(u);log('Device voice announcement played')}
async function importList(){S.playlistName=val('playlistName')||S.playlistName;S.playlistUrl=val('playlistUrl')||S.playlistUrl;S.platform=val('platform')||'suno';save();log('Import started');render();try{if(S.platform!=='suno')throw Error('Automatic import is currently strongest for Suno. Save this source, then use Bulk Import for YouTube/Spotify/Amazon until their API keys are connected.');let r=await fetch('/api/suno-playlist?url='+encodeURIComponent(S.playlistUrl));let d=await r.json();if(!r.ok||!d.ok||!d.tracks?.length)throw Error(d.error||'No tracks found');S.tracks=d.tracks.map(t=>({title:t.title||'Untitled',artist:t.artist||'Suno',duration:t.duration||'3:00',audioUrl:t.audioUrl||'',sourceUrl:t.sourceUrl||''}));S.current=0;log('Imported '+S.tracks.length+' tracks');save();render()}catch(e){alert(e.message);log('Import issue: '+e.message);render()}}
function bulk(){let rows=val('bulk').split('\n').map(x=>x.trim()).filter(Boolean);if(!rows.length)return;S.tracks=rows.map(r=>{let p=r.split('|').map(x=>x.trim());return{title:p[0]||'Untitled',artist:p[1]||'Unknown',duration:p[2]||'3:00',audioUrl:p[3]||''}});S.current=0;save();render()}
function play(){S.playing=true;let t=tr();if(t.audioUrl){audio.src=t.audioUrl;audio.play().catch(()=>alert('Direct audio stream is protected or unavailable. Queue control still works.'))}log('Playing '+t.title);save();render()}
function pause(){audio.pause();S.playing=false;save();render()}
function skip(n){S.current=(S.current+n+S.tracks.length)%S.tracks.length;if(S.playing)play();else{save();render()}}
async function verify(){S.address=val('address')||S.address;log('Verifying location');render();try{let r=await fetch('/api/geocode?address='+encodeURIComponent(S.address));let d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'No match');S.lat=String(d.latitude);S.lon=String(d.longitude);S.locationNote=(d.fallback?'Fallback location loaded. Use Device GPS at the resort to refine. ':'Verified: ')+(d.matchedAddress||S.address);S.weather='Location ready. Run Weather Check.';save();render()}catch(e){alert('Location verification failed: '+e.message);log('Location failed')}}
function deviceLoc(){navigator.geolocation?.getCurrentPosition(p=>{S.lat=p.coords.latitude.toFixed(6);S.lon=p.coords.longitude.toFixed(6);S.locationNote='Device GPS captured with about '+Math.round(p.coords.accuracy||0)+'m accuracy. Use this if phone is at the resort speakers.';save();render()},()=>alert('Device location permission failed.'),{enableHighAccuracy:true,timeout:12000})}
async function weather(){if(!S.lat||!S.lon){S.weather='Verify location first.';save();render();return}try{let r=await fetch(`/api/weather?lat=${S.lat}&lon=${S.lon}&radiusMiles=${+S.radius||10}`);let d=await r.json();if(!d.ok)throw Error(d.error||'Weather failed');S.weather=d.summary;if(d.threat){pause();speak('Attention guests. Weather activity has been detected nearby. Please exit the pool area and move indoors immediately.')}save();render()}catch(e){S.weather='Weather check failed: '+e.message;save();render()}}
function addSched(){let msg=val('schedMsg'), first=val('schedTime'), repeat=+val('schedRepeat')||1, interval=+val('schedInterval')||10;if(!msg)return;S.schedule.unshift({id:Date.now(),msg,next:first?new Date(first).getTime():Date.now()+60000,repeat,interval,done:0,on:true});save();render()}
function tick(){let n=Date.now(),c=false;S.schedule.forEach(s=>{if(s.on&&s.done<s.repeat&&n>=s.next){speak(s.msg);s.done++;s.next=n+s.interval*60000;if(s.done>=s.repeat)s.on=false;c=true}});if(c){save();render()}}
function head(){return `<header class="top"><div class="brand"><b>SS</b><span>Serenity Shores<small>Poolside Radio · V${VERSION}</small></span></div><div class="tog"><button id="homeBtn" class="${S.screen==='home'?'active':''}">Home</button><button id="cmdBtn" class="${S.screen!=='home'?'active':''}">Command</button></div></header>`}
function home(){let t=tr();return `${head()}<main class="home"><section class="hero"><div><p class="tag">LIVE RESORT STATION · V${VERSION}</p><h1>Poolside Radio</h1><p class="sub">Music, announcements, birthdays, daily messages, and weather-aware safety for Serenity Shores.</p><div class="actions"><button id="playHome">${S.playing?'Pause':'Play Station'}</button><button id="skipHome" class="secondary">Skip</button></div></div><aside><b>Weather Monitor</b><p>${esc(S.weather)}</p></aside></section><section class="now"><div class="art">SS<span>Radio</span></div><div><p class="tag teal">NOW PLAYING</p><h2>${esc(t.title)}</h2><p>${esc(t.artist)} · ${esc(t.duration)}</p><div class="bar"><i></i></div><p>${esc(S.playlistName)}</p></div></section><section class="cards"><div class="card"><h3>Up Next</h3>${S.tracks.slice(S.current+1,S.current+5).map(x=>`<p class="line"><b>${esc(x.title)}</b><span>${esc(x.artist)}</span></p>`).join('')||'<p>No more queued songs.</p>'}</div><div class="card"><h3>Today</h3><p>${esc(S.owner)}</p><p>${esc(S.manager)}</p></div></section></main>`}
function login(){return `${head()}<main class="wrap"><section class="card login"><h1>Command Center</h1><p>Protected controls. PIN is 7900.</p><input id="pin" inputmode="numeric" type="password" placeholder="PIN"><button id="login">Enter</button></section></main>`}
function tabs(){let a=[['station','Station'],['announce','Announce'],['schedule','Schedule'],['weather','Weather'],['voice','Voice']];return `<nav class="tabs">${a.map(x=>`<button data-tab="${x[0]}" class="${S.tab===x[0]?'on':''}">${x[1]}</button>`).join('')}</nav>`}
function command(body){return `${head()}<main class="wrap"><div class="version">Command Center · Version ${VERSION}</div>${tabs()}${body}</main>`}
function station(){return command(`<section class="panel"><h1>Music Source & Queue</h1><p>Primary automatic import: Suno. Similar platforms are supported as saved sources and bulk imports now; deeper API integrations can be connected when keys/terms allow.</p><label>Source<select id="platform"><option value="suno">Suno automatic import</option><option value="youtube">YouTube reference / manual import</option><option value="spotify">Spotify reference / manual import</option><option value="amazon">Amazon reference / manual import</option></select></label><label>Playlist Name<input id="playlistName" value="${esc(S.playlistName)}"></label><label>Playlist URL<input id="playlistUrl" value="${esc(S.playlistUrl)}"></label><div class="actions"><button id="saveStation">Save</button><button id="import">Import</button><button id="playCmd" class="secondary">${S.playing?'Pause':'Play'}</button><button id="skipCmd" class="secondary">Skip</button></div></section><section class="panel"><h2>Queue</h2>${S.tracks.map((t,i)=>`<div class="q ${i===S.current?'cur':''}"><b>${i+1}. ${esc(t.title)}</b><span>${esc(t.artist)} · ${esc(t.duration)}</span><button data-song="${i}">Play</button></div>`).join('')}</section><section class="panel"><h2>Universal Bulk Import</h2><p>Works for any platform after you paste song lines: Title | Artist | Duration | optional audio URL</p><textarea id="bulk">${S.tracks.map(t=>`${t.title} | ${t.artist} | ${t.duration} | ${t.audioUrl||''}`).join('\n')}</textarea><button id="bulkBtn">Save Bulk Import</button></section>`)}
function announce(){return command(`<section class="panel"><h1>Announcements</h1><textarea id="instant">${esc(S.instant)}</textarea><div class="actions"><button id="speak">Speak Now</button><button class="secondary" id="umbrellas">Close Umbrellas</button><button class="secondary" id="closing">Pool Closing</button></div></section><section class="panel"><h2>Birthday</h2><input id="birthdayName" placeholder="Guest name" value="${esc(S.birthdayName)}"><textarea id="birthdayText">${esc(S.birthdayText)}</textarea><button id="birthday">Speak Birthday</button></section><section class="panel"><h2>Owner / Manager Messages</h2><textarea id="owner">${esc(S.owner)}</textarea><textarea id="manager">${esc(S.manager)}</textarea><button id="saveMsg">Save Messages</button></section>`)}
function schedule(){return command(`<section class="panel"><h1>Daily Programming</h1><textarea id="schedMsg" placeholder="Message to play"></textarea><div class="grid3"><input id="schedTime" type="datetime-local"><input id="schedRepeat" type="number" value="3"><input id="schedInterval" type="number" value="10"></div><button id="addSched">Add Schedule</button></section><section class="panel"><h2>Scheduled</h2>${S.schedule.map(s=>`<div class="q"><b>${esc(s.msg)}</b><span>${s.done}/${s.repeat} · ${s.on?'next '+new Date(s.next).toLocaleString():'complete'}</span><button data-del="${s.id}">Delete</button></div>`).join('')||'<p>No scheduled items.</p>'}</section>`)}
function weatherTab(){return command(`<section class="panel"><h1>Location Verification</h1><p>Default is Serenity Shores. If public geocoding fails, the app uses a resort-area fallback and lets you refine with Device GPS.</p><label>Address<input id="address" value="${esc(S.address)}"></label><div class="actions"><button id="verify">Verify Address</button><button id="device" class="secondary">Use Device GPS</button><button id="weatherCheck" class="secondary">Weather Check</button></div><div class="grid3"><label>Latitude<input id="lat" value="${esc(S.lat)}"></label><label>Longitude<input id="lon" value="${esc(S.lon)}"></label><label>Radius<input id="radius" value="${esc(S.radius)}"></label></div><button id="saveLoc">Save Location</button><div class="status"><b>${esc(S.locationNote)}</b><p>${esc(S.weather)}</p></div></section>`)}
function voice(){let device=bestVoices().map(v=>`<option value="${esc(v.name)}" ${v.name===S.deviceVoice?'selected':''}>${esc(v.name)} · ${esc(v.lang)}</option>`).join('');return command(`<section class="panel"><h1>Voice Studio</h1><p>AI Voice sounds more natural. It requires OPENAI_API_KEY in Vercel. Device Voice is free but limited by iPhone/Safari.</p><label>Voice Mode<select id="voiceMode"><option value="ai">Natural AI Voice</option><option value="device">Free Device Voice</option></select></label><label>AI Voice<select id="aiVoice"><option value="marin">Marin - clear resort voice</option><option value="coral">Coral - warm</option><option value="nova">Nova - bright</option><option value="onyx">Onyx - deep</option><option value="shimmer">Shimmer - friendly</option><option value="sage">Sage - calm</option></select></label><label>Best English Device Voice<select id="deviceVoice"><option value="">Best available</option>${device}</select></label><div class="grid2"><label>Speed<input id="rate" type="range" min="0.75" max="1.15" step=".01" value="${S.voiceRate}"></label><label>Pitch<input id="pitch" type="range" min=".85" max="1.15" step=".01" value="${S.voicePitch}"></label></div><div class="actions"><button id="saveVoice">Save Voice</button><button id="testVoice" class="secondary">Test Voice</button></div></section>`)}
function render(){let html=S.screen==='home'?home():!S.admin?login():({station,announce,schedule,weather:weatherTab,voice}[S.tab]||station)();document.getElementById('app').innerHTML=html;bind()}
function bind(){if($('homeBtn'))$('homeBtn').onclick=()=>set('home');if($('cmdBtn'))$('cmdBtn').onclick=()=>set('command');if($('login'))$('login').onclick=()=>{if(val('pin')===PIN){S.admin=true;S.screen='command';S.tab='station';save();render()}else alert('Wrong PIN')};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;save();render()});if($('playHome'))$('playHome').onclick=()=>S.playing?pause():play();if($('skipHome'))$('skipHome').onclick=()=>skip(1);if($('platform'))$('platform').value=S.platform;if($('saveStation'))$('saveStation').onclick=()=>{S.platform=val('platform');S.playlistName=val('playlistName');S.playlistUrl=val('playlistUrl');save();render()};if($('import'))$('import').onclick=importList;if($('playCmd'))$('playCmd').onclick=()=>S.playing?pause():play();if($('skipCmd'))$('skipCmd').onclick=()=>skip(1);document.querySelectorAll('[data-song]').forEach(b=>b.onclick=()=>{S.current=+b.dataset.song;play()});if($('bulkBtn'))$('bulkBtn').onclick=bulk;if($('speak'))$('speak').onclick=()=>{S.instant=val('instant');save();speak(S.instant)};if($('umbrellas'))$('umbrellas').onclick=()=>speak('Attention guests, please close all umbrellas and secure loose items. Thank you.');if($('closing'))$('closing').onclick=()=>speak('Attention guests, the pool will be closing soon. Please gather your belongings.');if($('birthday'))$('birthday').onclick=()=>{S.birthdayName=val('birthdayName');S.birthdayText=val('birthdayText');save();speak(`Happy birthday ${S.birthdayName}. ${S.birthdayText}`)};if($('saveMsg'))$('saveMsg').onclick=()=>{S.owner=val('owner');S.manager=val('manager');save();render()};if($('addSched'))$('addSched').onclick=addSched;document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{S.schedule=S.schedule.filter(x=>String(x.id)!==String(b.dataset.del));save();render()});if($('verify'))$('verify').onclick=verify;if($('device'))$('device').onclick=deviceLoc;if($('weatherCheck'))$('weatherCheck').onclick=weather;if($('saveLoc'))$('saveLoc').onclick=()=>{S.address=val('address');S.lat=val('lat');S.lon=val('lon');S.radius=+val('radius')||10;save();render()};if($('voiceMode'))$('voiceMode').value=S.voiceMode;if($('aiVoice'))$('aiVoice').value=S.aiVoice;if($('saveVoice'))$('saveVoice').onclick=()=>{S.voiceMode=val('voiceMode');S.aiVoice=val('aiVoice');S.deviceVoice=val('deviceVoice');S.voiceRate=val('rate');S.voicePitch=val('pitch');save();render()};if($('testVoice'))$('testVoice').onclick=()=>speak('This is Serenity Shores Poolside Radio version '+VERSION+'. This is a natural voice test for resort announcements.')}
function loadVoices(){voices=speechSynthesis?.getVoices?.()||[];render()}
if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=loadVoices;loadVoices()}else render();setInterval(tick,10000);